sudo: required
dist: trusty
language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - cmake --version
  - mkdir build && cd build && cmake ..
  - cmake --build build --target all
  - CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
