sudo: required
language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target all
  - CTEST_OUTPUT_ON_FAILURE=1 cmake --build . --target test
